USE PRACTISE;

                                                     /* FINANCIAL ANALYSIS */

/* TOTAL MEDICIAL COST */
SELECT CONCAT(ROUND(SUM(`MEDICATION COST`)/1000,0), ' K') AS 'TOTAL MEDICATION COST'
FROM VISITS;

/* TOTAL INSURANCE COVERAGE */
SELECT CONCAT(ROUND(SUM(`INSURANCE COVERAGE`)/100000,0), ' M') AS 'TOTAL INSURANCE COVERAGE'
FROM VISITS;

/* TOTAL TREATMENT COST */
SELECT SUM(`TREATMENT COST`) AS 'TOTAL TREATMENT COST'
FROM VISITS;

/* Total Patients */
SELECT COUNT(`PATIENT ID`) AS "Total Patients Visit"
FROM VISITS;


/* Billing Cost */

SELECT SUM(`TREATMENT COST`+`MEDICATION COST`) AS "Total billing Cost"
FROM VISITS;

/* VISIT TYPE OF PATIENTS VISITED */

SELECT `PATIENT ID`,
CASE
WHEN `EMERGENCY VISIT`="NO" THEN "Non-Emergency"
ELSE "EMERGENCY"
END AS 'VISIT TYPE'
FROM VISITS;

/* TOTAL NO. OF PATIENT SATISFACTION SCORE */
SELECT COUNT(`PATIENT SATISFACTION SCORE`)
FROM VISITS;

